name: Edge TPU compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install 'numpy<=1.24.0' 'tensorflow-gpu>=2.4.0'
    
    - name: Install Edge TPU compiler
      run : |
        chmod +x compiler/compiler.sh
        ./compiler/compiler.sh
        edgetpu_compiler -v

    - name: Compile and test
      run: |
        python -m unittest
